action/debootstrap: make suite property mandatory for debootstrap action
go-debos/debos pull request #267
Opened 2021-07-22 03:55 UTC by vigneshraman

Check if suite property is present for debootstarp action and contains
a string. If suite is not present, exit with an error.

Signed-off-by: Vignesh Raman <vignesh.raman@collabora.com>

2021-07-23 13:19 UTC, obbardc commented
hmm, may be better to set a default suite (`main` for debian) and hope debootstrap complains for other distros ;-)

2021-07-28 05:52 UTC, vigneshraman commented
> hmm, may be better to set a default suite (`main` for debian) and hope debootstrap complains for other distros ;-)

default mirror is http://deb.debian.org/debian
default component is main

So for suite can we use 'stable' as default ?

2021-08-24 08:47 UTC, obbardc requested changes
two small nits

2021-08-24 08:47 UTC, obbardc commented on actions/debootstrap_action.go
> +	if len(d.Suite) == 0 {
move to `Verify` function so that we can error out early

2021-08-24 08:47 UTC, obbardc commented on actions/debootstrap_action.go
> +		return fmt.Errorf("'suite' is a mandatory property for Debootstrap Action")
```suggestion
		return fmt.Errorf("suite property not specified")
```

2021-08-24 11:09 UTC, vigneshraman commented
@obbardc, have updated the commit.

2023-07-17 08:36 UTC, obbardc approved these changes

2023-08-04 09:34 UTC, merged