Reverse the exitcode initialization value
go-debos/debos pull request #278
Opened 2021-08-09 12:39 UTC by eds-collabora

2021-08-09 18:49 UTC, obbardc requested changes

2021-08-09 18:49 UTC, obbardc commented on cmd/debos/debos.go
>  		if ok && flagsErr.Type == flags.ErrHelp {
```suggestion
		if flagsErr, ok := err.(*flags.Error); ok && flagsErr.Type == flags.ErrHelp {
```

2021-08-09 18:49 UTC, obbardc commented on cmd/debos/debos.go
>  	}
also looks like the recipe tests fail, can you look into that?

2021-08-09 18:50 UTC, obbardc commented on cmd/debos/debos.go
>  		"no_proxy",
might as well squash the commits while here

2021-08-09 20:43 UTC, eds-collabora commented
Summary of comments on this code to date:

- [ ] [Restore ownership of commit](https://github.com/santoshmahto7/debos/commit/d0f1d97797ec2674c94ab4581a66bc5a7f5c849d#commitcomment-53539606)
- [ ] [Avoid needless else block](https://github.com/santoshmahto7/debos/commit/d0f1d97797ec2674c94ab4581a66bc5a7f5c849d#r53539427)

2021-08-11 17:46 UTC, evelikov commented
In case it matters, the PR is:
```Reviewed-by: Emil Velikov <emil.velikov@collabora.com>```

If it were me, I would squash all the patches, adding a small note at the bottom for the extra changes wrt the original. Not a huge deal either way. Example:
```
...
This commit reverses the logic of the exitcode: it is initialized to 1
(i.e. failure), and it is set to 0 (i.e. success) only if Debos has
reached the end of the things it has to do (or for the help message).

Signed-off-by: Gaël PORTAY <gael.portay@collabora.com>

[Ed Smith]
 - Merge lines …
 - Fix exit behaviour when using fakemachine …
Signed-off-by: ... < if the project needs it, not sure
```

2021-08-13 12:48 UTC, obbardc commented
> Btw would be nice to hear from @sjoerdsimons what testing he had in plan in the earlier PR #198.

the comment was:
> testing of the various failure and test cases and with both kvm and non-fakemachine runs

2021-08-16 10:04 UTC, obbardc commented on docker/exitcode-test.yaml
> +version: '3.6'
can we just run all the tests together at the same time and not have a separate docker-compose ?

we probably need to implement a testing strategy first as a separate MR ;-)

2021-08-16 14:30 UTC, obbardc commented on tests/exit_test/bad.yaml
> +    chroot: false
drop this line

2021-08-16 14:30 UTC, obbardc commented on tests/exit_test/bad.yaml
> +    command: not-a-command
how about `exit 1`

2021-08-16 14:30 UTC, obbardc commented on tests/exit_test/good.yaml
> +    chroot: false
drop

2021-08-16 14:30 UTC, obbardc commented on tests/exit_test/good.yaml
> +    command: ls
exit 0

2021-08-16 14:31 UTC, obbardc commented on tests/exit_test/good.yaml
> +    command: ls
(for consistency)

2021-09-09 12:29 UTC, evelikov commented
With a bunch of tests in place (thanks Ed), can we get this trivial PR merged?

2022-01-07 11:47 UTC, obbardc commented
I took another look at this and wasn't happy; decided it would be cleaner to rework the panics in the code to bubbled-up errors: https://github.com/go-debos/fakemachine/pull/74

2024-01-13 16:19 UTC, sjoerdsimons commented
@obbardc would probably be worth picking up the tests that were added here even if you ended up doing the error handlign improvements in another way?

2024-01-15 10:43 UTC, obbardc commented
> @obbardc would probably be worth picking up the tests that were added here even if you ended up doing the error handlign improvements in another way?

Yeah, I will pick the tests up from this PR and cherry pick onto !303. Once that is done I will close this PR.

2025-06-26 19:28 UTC, daissi commented
I close this PR, since I cherry-picked relevant commits in https://github.com/go-debos/debos/pull/555 which was recently merged.

2025-06-26 19:28 UTC, closed without merging