actions/image-partition: allow extended and logical
go-debos/debos pull request #296
Opened 2021-11-05 04:52 UTC by daichifukui

This commit allows us to create extended or logical
partitions on MBR partition table (msdos) in order to
address the following issues:

* Because part-type for parted is hardcoded with primary,
we cannot create more than 4 partitions using extended and
logical.

* Even if we manage to create extended and logical partitions,
the verificaton step fails because the Verify function assumes
that the partition number is always sequetially incremental.

This commit makes it possible that if the number of partitions
is more than 4, 3 of them are automatically created as primary,
1 of them is extended, and the remaining partitions are logical.

Signed-off-by: Daniel Sangorrin <daniel.sangorrin@toshiba.co.jp>
Signed-off-by: Daichi Fukui <daichi1.fukui@toshiba.co.jp>

2021-11-05 04:53 UTC, daichifukui commented
This is related to https://github.com/go-debos/debos/issues/293

2022-06-27 01:11 UTC, daichifukui commented
Hi.

It's been a while since we began this discussion.
Does anyone have an opinion or feedback on this idea?

2023-12-30 21:44 UTC, sjoerdsimons requested changes

2023-12-30 21:44 UTC, sjoerdsimons commented on actions/image_partition_action.go
> +			if cap(i.Partitions) <= 4 {
```suggestion
			if len(i.Partitions) <= 4 {
```
cap is the capacity of the  array; the actual length might be shorter

2023-12-30 21:44 UTC, sjoerdsimons commented on actions/image_partition_action.go
> +		if idx == 3 && cap(i.Partitions) > 4 {
```suggestion
		if idx == 3 && len(i.Partitions) > 4 {
```
same

2023-12-30 21:44 UTC, sjoerdsimons commented on actions/image_partition_action.go
> +			tmp_n          := cap(i.Partitions)-1
```suggestion
			tmp_n          := len(i.Partitions)-1
```

2024-01-13 13:33 UTC, sjoerdsimons approved these changes

2024-01-13 15:32 UTC, merged

2024-01-18 22:05 UTC, robertkirkman commented
Hi I don't know enough about the project to know how to create a minimal reproducible example, but when i use [this](https://github.com/foxlet/VaporOS/blob/master/vapor-steamdeck-main.yaml) file with `debos`, if I use commit 03ec3cbfab6a73087ebbb58317f65e117342c1ba of `debos`  it works but if I use commit da773ccbc899d2f5b236f80db303062693f6f2b6 or any of the recent commits after that, the `debos` command gets stuck inside the fakemachine because of a partition named "extended" getting incorrectly created in the wrong place even though the `.yaml` file specifies `gpt` and not `mbr`

2024-01-18 22:14 UTC, obbardc commented
@robertkirkman Can you please open a separate issue about this so it doesn't get lost ?

2024-01-18 23:34 UTC, robertkirkman commented
ok I opened that here #473