Check if artifactdir exists early
go-debos/debos pull request #429
Opened 2023-08-11 14:00 UTC by obbardc

Currently debos fails if an action attempts to use artifactdir and it doesn't exist on the host:

  $ debos --artifactdir=out rpi64/debimage-rpi64.yaml
  Action `image-partition` failed at stage PreMachine, error: open /home/obbardc/projects/debos/debos-recipes/out/debian-rpi64.img: no such file or directory

Check that artifactdir exists early and return an error in case that it does not exist.

Closes: #426

2023-08-21 11:26 UTC, obbardc commented on cmd/debos/debos.go
> +		exitcode = 1
This will conflict with #303

2024-01-13 15:35 UTC, sjoerdsimons commented on cmd/debos/debos.go
> +	if _, err := os.Stat(context.Artifactdir); os.IsNotExist(err) {
should check if it's a Dir as well :)

2024-01-13 15:35 UTC, sjoerdsimons requested changes
check if it's a dir not just that it's "something"

2025-02-16 10:29 UTC, sjoerdsimons commented
@obbardc any change you can address the small open comment ?

2025-02-16 16:20 UTC, obbardc commented
I added the additional check.

2025-06-27 00:14 UTC, obbardc commented
superceeded by #556

2025-06-27 00:14 UTC, closed without merging