debos: Warn if parsed memory/scratchsize may be too small
go-debos/debos pull request #510
Opened 2024-07-01 10:53 UTC by obbardc

Since the --memory and --scratchsize arguments are parsed with human-readable suffixes into bytes (e.g 2048MB or 2GB), if a user does not put a suffix the arguments are parsed as bytes which can cause issues later when a user sets the memory to be 2048 assuming it will be parsed as MB.

Change the documentation to match reality and also add a warning if the user has set either parameter less than the recommended default.

Closes: #509

2024-11-14 17:38 UTC, daissi commented
Something is wrong with --scratchsize:
```
./debos ../debos-recipes/rpi3/debimage-rpi3.yaml --scratchsize 100MB -m 100MB
2024/11/14 18:35:32 WARNING: Memory size of 100MB is less than recommended 2048MB
2024/11/14 18:35:32 WARNING: Scratch size of 95MB is less than recommended 2048MB
```
While is works for --memory, the conversion for scratchsize doesn't give us the same value 100MB vs 95MB

2024-11-14 18:28 UTC, obbardc commented
> Something is wrong with --scratchsize:
> 
> ```
> ./debos ../debos-recipes/rpi3/debimage-rpi3.yaml --scratchsize 100MB -m 100MB
> 2024/11/14 18:35:32 WARNING: Memory size of 100MB is less than recommended 2048MB
> 2024/11/14 18:35:32 WARNING: Scratch size of 95MB is less than recommended 2048MB
> ```
> 
> While is works for --memory, the conversion for scratchsize doesn't give us the same value 100MB vs 95MB

I guess that is because for scratchsize we convert to bytes with `units.FromHumanSize` but for memory we do not :-).

Perhaps we should unify this by:

1) using `units.FromHumanSize` to convert for both scratchsize & memory.
2) convert to MB using forumula `/ 1000 / 1000` for both variables instead of `/ 1024 / 1024`. That should make the printed number the same.

To be honest, I threw this together quickly just for some feedback. Happy to rework it.

2024-11-15 11:22 UTC, daissi commented
I would say let's use for both `units.FromHumanSize` for consistency :) This should avoid confusion.

2025-02-16 10:22 UTC, sjoerdsimons commented
> I would say let's use for both `units.FromHumanSize` for consistency :) This should avoid confusion.

go-units isn't great `FromHumanSize` is really more for disk sizes (decimal units) while `RamInBytes`  follows binary units which is more suitable for memory (see https://en.wikipedia.org/wiki/Byte#Multiple-byte_units).  However annoyingly it will accept both MiB and MB for either, but will parse them according to the predetermined table.... So if you do `FromHumanSize("100Mib")` you'll get `100 * 1000**2` 

For this PR assuming a MB for disk is `1000**2` while a MB for ram is `1024**2`  would be the correct solution. Ideally FromHumanSize to recognize MiB as binary, but doesn't look like that will happen ([go-units issue](https://github.com/docker/go-units/issues/31)). However the expectation of what an `MB` is sadly just is different depending on the context :man_shrugging:

2025-02-16 10:24 UTC, sjoerdsimons requested changes
see comment :)

2025-02-16 16:14 UTC, obbardc commented
@sjoerdsimons made teh changes according to your suggestions :-)

2025-02-17 07:59 UTC, sjoerdsimons requested changes
Sorry i should have looked at the sizes more closely yesterday, i just ended up being in the 1024 vs 1000 rathole too much ;) TL;DR I think giving warnings is great, but the current threshold seems a bit low, if you run on a small VM (e.g. 1 or 2G memory instance) then having a smaller then 2G memory size is fine.  Especially if you use a scratchdisk, where the VMs memory mostly just needs to be enough to run apt.

So lets be a bit less trigger-happy on these warnings, as you said it's mostly for people forgetting to add `M`. Which we'll still easily filter out even with a very conservative "accepted" minimum

2025-02-17 07:59 UTC, sjoerdsimons commented on cmd/debos/debos.go
> +			log.Printf("WARNING: Memory size of %dMB is less than recommended 2048MB\n", memsizeMB)
Fwiw less then  2G is fine; It's probably when it's less then say 512m or even 256 i'd start really questioning  things.

2025-02-17 07:59 UTC, sjoerdsimons commented on cmd/debos/debos.go
> +				log.Printf("WARNING: Scratch size of %dMB is less than recommended 2048MB\n", scratchsizeMB)
fwiw scratchsize is in particular surprising when it's e.g. less then the vm's memory as that makes it somewhat pointless.  2G is quite a bit for most systems we tend to be build, for most 1G or even 512M would still be fine.

2025-02-17 14:30 UTC, obbardc commented on cmd/debos/debos.go
> +			log.Printf("WARNING: Memory size of %dMB is less than recommended 2048MB\n", memsizeMB)
changed it to say "recommended minimum" and set that limit to be 256M

2025-02-17 14:30 UTC, obbardc commented on cmd/debos/debos.go
> +				log.Printf("WARNING: Scratch size of %dMB is less than recommended 2048MB\n", scratchsizeMB)
changed it to say "recommended minimum" and set that limit to be 512M

2025-02-17 14:31 UTC, obbardc commented on cmd/debos/debos.go
> +				log.Printf("WARNING: Scratch size of %dMB is less than recommended 2048MB\n", scratchsizeMB)
I could check if its smaller than RAM here, but i don't think it's worth it.

2025-02-18 10:56 UTC, merged