actions: Add mmdebstrap action
go-debos/debos pull request #515
Opened 2024-08-25 21:08 UTC by nbuchwitz

Add mmdebstrap [1] as a faster and more flexible alternative to debootstrap.

[1] https://gitlab.mister-muffin.de/josch/mmdebstrap

# Comparison to deboostrap

Example recipe on a Raspberry Pi 5 in docker container with KVM enabled:
```
---
{{- $architecture := or .architecture "arm64"}}
{{- $tool := or .tool "mmdebstrap" }}
architecture: {{$architecture}}

actions:
  - action: {{ $tool }}
    suite: bookworm
    variant: minbase

  - action: apt
    description: Install some base packages
    packages:
      - procps
```

With `deboostrap`:
```
real    0m53.590s
user    0m38.792s
sys     0m25.345s

```

With `mmdebstrap`:
```
real    0m33.400s
user    0m24.239s
sys     0m8.838s
```

=> 20 seconds faster

2024-08-25 21:14 UTC, obbardc commented
looks fine to me, but I remember @sjoerdsimons had some reservations about ai ply integrating another tool and would rather rewrite debootstrap in go utilising more efficient system libs (debootstrap is single threaded, assumes not much is installed on the target system etc etc)

2024-08-25 21:24 UTC, nbuchwitz commented
> looks fine to me, but I remember @sjoerdsimons had some reservations about ai ply integrating another tool and would rather rewrite debootstrap in go utilising more efficient system libs (debootstrap is single threaded, assumes not much is installed on the target system etc etc)

Thanks for the fast response and the heads up. `mmdebstrap` deals with some major issues of `deboostrap` (some of them are even wontfix, like multiple mirrors etc). So maybe it is worth considering it (as an intermediate solution). Looking forward to @sjoerdsimons feedback

2025-02-12 06:57 UTC, iwamatsu commented
Hi, 

If you plan to apply this feature, please consider mmdebstrap's include variable feature.
I create a patch for this  feature:
  https://github.com/iwamatsu/debos/commit/b9f3f28e78ebbd3b6d4b79682f7d230bf07e4365

2025-02-13 14:34 UTC, tboehler1 requested changes

2025-02-13 14:34 UTC, tboehler1 commented on actions/mmdebstrap_action.go
> +	}
Making this part of a defer at the beginning of the function avoids problems down the line if more lines were added after the mmdebstrap call and before the removal of the resolv.conf that would exit our early on error. That way, if the resolv.conf exists, it will *always* be removed, and there's no chance for mistakes.

2025-02-14 07:31 UTC, tboehler1 commented on actions/mmdebstrap_action.go
> +	}
It's idiomatic go to put function cleanup for both normal return and error in a defer and should something like recovering from an error here ever be implemented this trivial change could prevent a potential bug. But it's your choice.

2025-02-16 10:55 UTC, sjoerdsimons commented
> > Hi,
> > If you plan to apply this feature, please consider mmdebstrap's include variable feature. I create a patch for this feature: [iwamatsu@b9f3f28](https://github.com/iwamatsu/debos/commit/b9f3f28e78ebbd3b6d4b79682f7d230bf07e4365)
> 
> Thanks! I've picked your commit into this PRs branch

Fwiw this makes the settings different from debootstrap; With debootstrap there were a whole bunch of issues around doing includes this early, though hopefully mmdebstrap fixes that because it actually uses apt. 

That said i'm not sure about this change; Are there use-cases where this has real benefits over mmdebstrap + apt actions to install the extra packages?

2025-02-16 10:59 UTC, sjoerdsimons commented on actions/mmdebstrap_action.go
> +	d.Components = []string{"main"}
MergdUsr should be true by default

2025-02-16 11:00 UTC, sjoerdsimons commented on actions/mmdebstrap_action.go
> +	d.Components = []string{"main"}
ah you did make it a pointer nvm :)

2025-02-16 11:21 UTC, sjoerdsimons requested changes
Some small improvements; but overall looking nice..

Fwiw i've always been against other bootstrapping tools directly in debos; However it seems mmdebstrap actually got enough traction (with being used on the buildds now), that it seems a safe bet for a long-term viable tool

2025-02-16 11:21 UTC, sjoerdsimons commented on actions/mmdebstrap_action.go
> +		cmdline = append(cmdline, fmt.Sprintf("--architectures=%s", context.Architecture))
with mmdebstrap you can avoid this hack; just always set the `--architecture` option

2025-02-16 11:21 UTC, sjoerdsimons commented on actions/mmdebstrap_action.go
> +	}
This is the same flow as we have for debootstrap; so it's fine by me; 

Fwiw like in the debootstrap command if we run commands in the chroot later, you most likely actually want to have `resolv.conf` cleaned up at that point (as our chroot command helper has it's only `resolv.conf` handling).  In that case a defer would actually be wrong :)

That said this code is currently masking the `err` return from the mmdebstrap command, which is something that really should be fix

2025-02-16 11:21 UTC, sjoerdsimons commented on .github/workflows/ci.yaml
> +          - { name: "debian with mmdebstrap (amd64)", case: "debian", variables: "-t architecture:amd64 -t tool:mmdebstrap" }
Also add tests for arm64 and armhf to ensure different archs also work.. Feel free to change the commends to `debian (amd64, debootstrap)` and `debian (amd64, mmdebstrap)` rather then making mmdebstrap special

2025-02-16 12:48 UTC, nbuchwitz commented on actions/mmdebstrap_action.go
> +	}
Well spotted with the masked `err`, I've fixed it and will leave the rest of the logic as is in `debootstrap`.

2025-02-16 12:49 UTC, nbuchwitz commented on actions/mmdebstrap_action.go
> +		cmdline = append(cmdline, fmt.Sprintf("--architectures=%s", context.Architecture))
Fixed in latest force push

2025-02-16 12:49 UTC, nbuchwitz commented on .github/workflows/ci.yaml
> +          - { name: "debian with mmdebstrap (amd64)", case: "debian", variables: "-t architecture:amd64 -t tool:mmdebstrap" }
Fixed in latest force push

2025-02-18 11:40 UTC, nbuchwitz commented
Pipeline is also fixed, so this PR is ready for another round of feedback

2025-02-23 19:56 UTC, sjoerdsimons requested changes

2025-02-23 19:56 UTC, sjoerdsimons commented on actions/mmdebstrap_action.go
> +	// Be secure by default
Drop the leftover comment

2025-02-23 19:56 UTC, sjoerdsimons commented on actions/mmdebstrap_action.go
> +- merged-usr -- use merged '/usr' filesystem, true by default.
As i understand it correctly; it's not true by default but rather follows the distribution default; so this seems incorrect

2025-02-23 19:56 UTC, sjoerdsimons commented on actions/mmdebstrap_action.go
> +			cmdline = append(cmdline, "--include=usrmerge")
Open question whether this should be the method rather then using `/usr/share/mmdebstrap/hooks/merged-usr`  (which follows how deboostrap sets things up).

2025-02-23 19:57 UTC, sjoerdsimons commented
@nbuchwitz Just a small nitpicks left and a question; Fwiw please don't add more features in this MR, lets focus on getting it merged  :) Extra features can easily come as a follow-up

2025-02-23 22:35 UTC, nbuchwitz commented on actions/mmdebstrap_action.go
> +			cmdline = append(cmdline, "--include=usrmerge")
I really don't have strong feelings for either solution. Nevertheless, after some thinking,  `/usr/share/mmdebstrap/hooks/merged-usr` seems to be a good compromise, as a user can choose the other way (thanks to @iwamatsu's patch) by adding the `usrmerge` package to the `include` list.

2025-02-23 22:39 UTC, nbuchwitz commented on actions/mmdebstrap_action.go
> +- merged-usr -- use merged '/usr' filesystem, true by default.
I rephrased the help text in order to point out, that if the attribute is not specified it falls back to the distributions default.

2025-02-24 09:01 UTC, nbuchwitz commented on actions/mmdebstrap_action.go
> +			cmdline = append(cmdline, "--include=usrmerge")
Hm, tests are failed with the hooks script: I can reproduce the same issue with plain `mmdebstrap` and bullseye suite:

```
$ mmdebstrap --hook-dir=/usr/share/mmdebstrap/hooks/no-merged-usr --components=main --architectures=amd64 --variant=minbase bullseye rootfs.tar   
I: automatically chosen mode: unshare
I: amd64 cannot be executed natively, but transparently using qemu-user binfmt emulation
I: finding correct signed-by value...
done
I: automatically chosen format: tar
I: using /tmp/mmdebstrap.d4bPhIhmgf as tempdir
dpkg: warning: failed to open configuration file '/home/nbw/.dpkg.cfg' for reading: Permission denied
I: running --setup-hook directly: /usr/share/mmdebstrap/hooks/no-merged-usr/setup00.sh /tmp/mmdebstrap.d4bPhIhmgf
Warning: starting with Debian 12 (Bookworm), systems without merged-/usr are not supported anymore
dpkg-deb: building package 'usr-is-merged' in '/tmp/mmdebstrap.d4bPhIhmgf/tmp/tmp.zBxyHOzSaK/usr-is-merged.deb'.
dpkg: warning: failed to open configuration file '/home/nbw/.dpkg.cfg' for reading: Permission denied
Selecting previously unselected package usr-is-merged.
(Reading database ... 0 files and directories currently installed.)
Preparing to unpack .../usr-is-merged.deb ...
Unpacking usr-is-merged (1) ...
Setting up usr-is-merged (1) ...
I: running apt-get update...
done
I: downloading packages with apt...
done
I: extracting archives...
done
I: installing essential packages...
done
I: running --essential-hook directly: /usr/share/mmdebstrap/hooks/no-merged-usr/essential00.sh /tmp/mmdebstrap.d4bPhIhmgf
Reading package lists... Done
Building dependency tree... Done
usr-is-merged is already the newest version (1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
E: setup failed: E: command failed: /usr/share/mmdebstrap/hooks/no-merged-usr/essential00.sh
I: main() received signal PIPE: waiting for setup...
I: removing tempdir /tmp/mmdebstrap.d4bPhIhmgf...
```

2025-02-24 09:39 UTC, nbuchwitz commented on actions/mmdebstrap_action.go
> +			cmdline = append(cmdline, "--include=usrmerge")
Looks like `/usr/share/mmdebstrap/hooks/maybe-merged-usr` is the safer hook: It will not try to merge if unsupported and otherwise merge. I refactored the logic so `MergedUsr` is now a bool (like in debootstrap) which defaults to `true`. With this both debos actions should behave similar.

2025-02-24 10:58 UTC, sjoerdsimons commented on actions/mmdebstrap_action.go
> +			cmdline = append(cmdline, "--include=usrmerge")
Well if we set merged-user to true; it should really either fails or end up with merged user rather then a maybe-merged-usr :). @obbardc  was looking at improving the per-suite handling in #424, but yeah it's all a bit of nightmare.

I'll try to have a further look tonight as well; That said if mmdebstrap setting `merged-usr: true` only really works from bookworm onwards that's not the end of the world (something we can document). And as you said including `usrmerge` is a workaround for older ones?

2025-02-24 12:10 UTC, nbuchwitz commented on actions/mmdebstrap_action.go
> +			cmdline = append(cmdline, "--include=usrmerge")
Ok then let's keep the current approach (haven't force pushed my changed described above). In order to make the tests work again, we should change the `suite` to `bookworm` (makes sense anyway as it is stable and will become oldstable this year ...)?

2025-02-24 20:36 UTC, sjoerdsimons approved these changes

2025-02-24 21:12 UTC, merged